### ISSUE TITLE
pitch bend byte ordering

### ISSUE THREAD

**Issue by Pomax** [tigoe/SoundExamples#2]
https://tigoe.github.io/SoundExamples/midi-pitch-bend.html says to use `midiCommand(0xE0, msb, lsb);` but the MIDI spec says this should be `<pitch bend nibble> <channel nibble> 0LLLLLLL 0MMMMMMM` where L are the 7 least significant bits, and M are the 7 most significant bits. So that would be `midiCommand(0xE0, lsb, msb);`

**Comment by tigoe** [comment]
Fixed.
